CREATE TABLE hate2date(
   
id INTEGER(10) AUTO_INCREMENT NOT NULL,
name VARCHAR(20) NOT NULL,
email VARCHAR(100) NOT NULL,
occupation VARCHAR(100) NOT NULL,
relationshipType VARCHAR(250) NOT NULL,
location VARCHAR(20) NOT NULL,
password VARCHAR(35) NOT NULL,
imageURL VARCHAR(500),
bio VARCHAR(500) NOT NULL,
PRIMARY KEY (id)
);